## 量化交易平台配置

# 模拟环境配置
SIMULATION:
  QMT_PATH: 'D:\国金QMT交易端模拟\userdata_mini'
  ACCOUNT: '55005056'
  NAME: '模拟环境'
  PASSWORD: '259800'

# 实盘环境配置
PRODUCTION:
  QMT_PATH: 'D:\国金证券QMT交易端\userdata_mini'
  ACCOUNT: '8881667160'
  NAME: '实盘环境'

# 数据源配置
toshare_token: 'gx03013e909f633ecb66722df66b360f070426613316ebf06ecd3482'

# 数据库配置
DATABASE:
  host: '120.26.202.151'
  port: 3306
  user: 'root'
  password: '611698'
  database: 'stock_data'
  charset: 'utf8mb4'

# 兼容性配置（保持向后兼容）
QMT_PATH:
  - 'D:\国金QMT交易端模拟\userdata_mini'
  - 'D:\国金证券QMT交易端\userdata_mini'

account:
  - '55005056'
  - '8881667160'
